name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CUSTOM_VAR: ci-demo

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Run linting
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npm run lint
      - name: Use environment variable
        run: echo "Custom variable is $CUSTOM_VAR"
      - id: set-output
        run: echo "::set-output name=value::$(echo hello)"
      - name: Use output from previous step
        run: echo "Received value from previous step: ${{ steps.set-output.outputs.value }}"
